export const PRODUCTS_LIST_REQUEST = "PRODUCTS_LIST_REQUEST";
export const PRODUCTS_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCTS_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCTS_DETAILS_REQUEST = "PRODUCTS_DETAILS_REQUEST";
export const PRODUCTS_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCTS_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
